apiVersion: v1
kind: ServiceAccount
metadata:
  name: womba-index-all
  namespace: womba
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: womba-index-all-exec
  namespace: womba
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: womba-index-all-exec
  namespace: womba
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: womba-index-all-exec
subjects:
- kind: ServiceAccount
  name: womba-index-all
  namespace: womba

